---
- name: "Add an Apt signing key For Fluentbit"
  apt_key:
    url: "https://packages.fluentbit.io/fluentbit.key"
    id: "F209D8762A60CD49E680633B4FF8368B6EA0722A"
    state: "present"

- name: "Check that HTTPS transport is available to APT"
  apt:
    name: "apt-transport-https"
    state: "present"
    update_cache: "yes"

- name: "Ensure the package repository is up to date"
  apt_repository:
    repo: "deb https://packages.fluentbit.io/{{ ansible_distribution|lower }}/{{ ansible_distribution_release }} {{ ansible_distribution_release }} main"
    state: "present"

- name: "Update repositories cache and install td-agent-bit"
  apt:
    name: "td-agent-bit"
    update_cache: "yes"

- name: "Make and copy the configuration file"
  template:
    src: "etc/td-agent-bit/td-agent-bit.conf.j2"
    dest: "/etc/td-agent-bit/td-agent-bit.conf"
  notify: "reload td-agent"

- name: "Make and copy the additional parsers file"
  template:
    src: "etc/td-agent-bit/additional_parser.j2"
    dest: "/etc/td-agent-bit/{{ item.name }}.conf"
  with_items: '{{ sitewards__fluentbit__additional_parsers }}'
  when: sitewards__fluentbit__additional_parsers | length >0
  notify: "reload td-agent"

- name: "Start service td-agent-bit, if not running"
  service:
    name: "td-agent-bit"
    state: "started"
    enabled: "yes"
